var issue = [
  { 'severity': 3, 'type': 40201, 'sid': '0', 'extra': 'https://static-assets-web.flixcart.com/batman-returns/batman-returns/p/app.bbf6fe.css', 'fetched': true, 'code': 200, 'len': 67508, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'dir': 'i0' },
  { 'severity': 3, 'type': 40201, 'sid': '0', 'extra': 'https://static-assets-web.flixcart.com/batman-returns/batman-returns/p/callouts.490e71.css', 'fetched': true, 'code': 200, 'len': 67508, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'dir': 'i1' },
  { 'severity': 3, 'type': 40201, 'sid': '0', 'extra': 'https://static-assets-web.flixcart.com/batman-returns/batman-returns/p/fkvendor.9675c3.js', 'fetched': true, 'code': 200, 'len': 67508, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'dir': 'i2' },
  { 'severity': 3, 'type': 40201, 'sid': '0', 'extra': 'https://static-assets-web.flixcart.com/batman-returns/batman-returns/p/app.4f311c.js', 'fetched': true, 'code': 200, 'len': 67508, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'dir': 'i3' },
  { 'severity': 3, 'type': 40101, 'sid': '0', 'extra': 'injected \x27\x3csfi...\x3e\x27 tag seen in HTML', 'fetched': true, 'code': 200, 'len': 104048, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'dir': 'i4' },
  { 'severity': 2, 'type': 30501, 'sid': '0', 'extra': 'https://rukminim1.flixcart.com/www/25/25/promos/06/11/2017/88a36c83-806c-4523-9b9e-38085e342e83.png?q=100', 'fetched': true, 'code': 200, 'len': 67508, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'dir': 'i5' },
  { 'severity': 2, 'type': 30501, 'sid': '0', 'extra': 'https://img1a.flixcart.com/batman-returns/batman-returns/p/images/broken_link-49d9b.png', 'fetched': true, 'code': 200, 'len': 67508, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'dir': 'i6' },
  { 'severity': 1, 'type': 20205, 'sid': '0', 'extra': 'Responses too slow for time sensitive tests', 'fetched': true, 'code': 200, 'len': 104030, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'dir': 'i7' },
  { 'severity': 1, 'type': 20101, 'sid': '0', 'extra': 'dir traversal', 'fetched': false, 'error': 'Connection error', 'dir': 'i8' },
  { 'severity': 0, 'type': 10201, 'sid': '0', 'extra': 'SN', 'fetched': true, 'code': 200, 'len': 18, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'dir': 'i9' }
];
