var child = [
  { 'dupe': false, 'type': 8, 'name': 'NDFGAW4XQ65NDKUU:1', 'dir': 'c0', 'linked': 2, 'url': 'https://www.flipkart.com/reviews/NDFGAW4XQ65NDKUU:1', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 8, 'name': 'NDFGAW4XQ65NDKUU:144', 'dir': 'c2', 'linked': 2, 'url': 'https://www.flipkart.com/reviews/NDFGAW4XQ65NDKUU:144', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 8, 'name': 'NDFGAW4XQ65NDKUU:37', 'dir': 'c3', 'linked': 2, 'url': 'https://www.flipkart.com/reviews/NDFGAW4XQ65NDKUU:37', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 8, 'name': 'NDFGAW4XQ65NDKUU:38', 'dir': 'c4', 'linked': 2, 'url': 'https://www.flipkart.com/reviews/NDFGAW4XQ65NDKUU:38', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 8, 'name': 'NDFGAW4XQ65NDKUU:48', 'dir': 'c5', 'linked': 2, 'url': 'https://www.flipkart.com/reviews/NDFGAW4XQ65NDKUU:48', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 8, 'name': 'NDFGAW4XQ65NDKUU:59', 'dir': 'c6', 'linked': 2, 'url': 'https://www.flipkart.com/reviews/NDFGAW4XQ65NDKUU:59', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 8, 'name': 'NDFGAW4XQ65NDKUU:63', 'dir': 'c7', 'linked': 2, 'url': 'https://www.flipkart.com/reviews/NDFGAW4XQ65NDKUU:63', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 8, 'name': 'NDFGAW4XQ65NDKUU:64', 'dir': 'c8', 'linked': 2, 'url': 'https://www.flipkart.com/reviews/NDFGAW4XQ65NDKUU:64', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 8, 'name': 'NDFGAW4XQ65NDKUU:67', 'dir': 'c9', 'linked': 2, 'url': 'https://www.flipkart.com/reviews/NDFGAW4XQ65NDKUU:67', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 }
];
