var child = [
  { 'dupe': false, 'type': 64, 'name': 'fm=organic', 'dir': 'c0', 'linked': 2, 'url': 'https://www.flipkart.com/bolas-seedless-tunisian-dates/p/itm9a4a99b4acfdc?pid=NDFGXVVBQRGYT4TC&lid=LSTNDFGXVVBQRGYT4TCLHURLP&marketplace=FLIPKART&store=eat/ltb&srno=b_1_28&otracker=browse&fm=organic&iid=en_id1m4MMKmeogfDFhupCa1sVpEhOai6z-vIj6BI5vYggPr0IGA6voo_XR1kyY7tzRLHBhCyBwOQMdU_NMdCmiZEKsf8s6I2Oz2HOgbXTo_9U%3D&ppt=None&ppn=None&ssid=usqtd7yqpc0000001713439805334', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 64, 'name': 'iid=en_id1m4MMKmeogfDFhupCa1sVpEhOai6z-vIj6BI5vYggPr0IGA6voo_XR1kyY7tzRLHBhCyBwOQMdU_NMdCmiZEKsf8s6I2Oz2HOgbXTo_9U=', 'dir': 'c1', 'linked': 2, 'url': 'https://www.flipkart.com/bolas-seedless-tunisian-dates/p/itm9a4a99b4acfdc?pid=NDFGXVVBQRGYT4TC&lid=LSTNDFGXVVBQRGYT4TCLHURLP&marketplace=FLIPKART&store=eat/ltb&srno=b_1_28&otracker=browse&fm=organic&iid=en_id1m4MMKmeogfDFhupCa1sVpEhOai6z-vIj6BI5vYggPr0IGA6voo_XR1kyY7tzRLHBhCyBwOQMdU_NMdCmiZEKsf8s6I2Oz2HOgbXTo_9U%3D&ppt=None&ppn=None&ssid=usqtd7yqpc0000001713439805334', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 64, 'name': 'lid=LSTNDFGXVVBQRGYT4TCLHURLP', 'dir': 'c2', 'linked': 2, 'url': 'https://www.flipkart.com/bolas-seedless-tunisian-dates/p/itm9a4a99b4acfdc?pid=NDFGXVVBQRGYT4TC&lid=LSTNDFGXVVBQRGYT4TCLHURLP&marketplace=FLIPKART&store=eat/ltb&srno=b_1_28&otracker=browse&fm=organic&iid=en_id1m4MMKmeogfDFhupCa1sVpEhOai6z-vIj6BI5vYggPr0IGA6voo_XR1kyY7tzRLHBhCyBwOQMdU_NMdCmiZEKsf8s6I2Oz2HOgbXTo_9U%3D&ppt=None&ppn=None&ssid=usqtd7yqpc0000001713439805334', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 64, 'name': 'marketplace=FLIPKART', 'dir': 'c3', 'linked': 2, 'url': 'https://www.flipkart.com/bolas-seedless-tunisian-dates/p/itm9a4a99b4acfdc?pid=NDFGXVVBQRGYT4TC&lid=LSTNDFGXVVBQRGYT4TCLHURLP&marketplace=FLIPKART&store=eat/ltb&srno=b_1_28&otracker=browse&fm=organic&iid=en_id1m4MMKmeogfDFhupCa1sVpEhOai6z-vIj6BI5vYggPr0IGA6voo_XR1kyY7tzRLHBhCyBwOQMdU_NMdCmiZEKsf8s6I2Oz2HOgbXTo_9U%3D&ppt=None&ppn=None&ssid=usqtd7yqpc0000001713439805334', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 64, 'name': 'otracker=browse', 'dir': 'c4', 'linked': 2, 'url': 'https://www.flipkart.com/bolas-seedless-tunisian-dates/p/itm9a4a99b4acfdc?pid=NDFGXVVBQRGYT4TC&lid=LSTNDFGXVVBQRGYT4TCLHURLP&marketplace=FLIPKART&store=eat/ltb&srno=b_1_28&otracker=browse&fm=organic&iid=en_id1m4MMKmeogfDFhupCa1sVpEhOai6z-vIj6BI5vYggPr0IGA6voo_XR1kyY7tzRLHBhCyBwOQMdU_NMdCmiZEKsf8s6I2Oz2HOgbXTo_9U%3D&ppt=None&ppn=None&ssid=usqtd7yqpc0000001713439805334', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 64, 'name': 'pid=NDFGXVVBQRGYT4TC', 'dir': 'c5', 'linked': 2, 'url': 'https://www.flipkart.com/bolas-seedless-tunisian-dates/p/itm9a4a99b4acfdc?pid=NDFGXVVBQRGYT4TC&lid=LSTNDFGXVVBQRGYT4TCLHURLP&marketplace=FLIPKART&store=eat/ltb&srno=b_1_28&otracker=browse&fm=organic&iid=en_id1m4MMKmeogfDFhupCa1sVpEhOai6z-vIj6BI5vYggPr0IGA6voo_XR1kyY7tzRLHBhCyBwOQMdU_NMdCmiZEKsf8s6I2Oz2HOgbXTo_9U%3D&ppt=None&ppn=None&ssid=usqtd7yqpc0000001713439805334', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 64, 'name': 'ppn=None', 'dir': 'c6', 'linked': 2, 'url': 'https://www.flipkart.com/bolas-seedless-tunisian-dates/p/itm9a4a99b4acfdc?pid=NDFGXVVBQRGYT4TC&lid=LSTNDFGXVVBQRGYT4TCLHURLP&marketplace=FLIPKART&store=eat/ltb&srno=b_1_28&otracker=browse&fm=organic&iid=en_id1m4MMKmeogfDFhupCa1sVpEhOai6z-vIj6BI5vYggPr0IGA6voo_XR1kyY7tzRLHBhCyBwOQMdU_NMdCmiZEKsf8s6I2Oz2HOgbXTo_9U%3D&ppt=None&ppn=None&ssid=usqtd7yqpc0000001713439805334', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 64, 'name': 'ppt=None', 'dir': 'c7', 'linked': 2, 'url': 'https://www.flipkart.com/bolas-seedless-tunisian-dates/p/itm9a4a99b4acfdc?pid=NDFGXVVBQRGYT4TC&lid=LSTNDFGXVVBQRGYT4TCLHURLP&marketplace=FLIPKART&store=eat/ltb&srno=b_1_28&otracker=browse&fm=organic&iid=en_id1m4MMKmeogfDFhupCa1sVpEhOai6z-vIj6BI5vYggPr0IGA6voo_XR1kyY7tzRLHBhCyBwOQMdU_NMdCmiZEKsf8s6I2Oz2HOgbXTo_9U%3D&ppt=None&ppn=None&ssid=usqtd7yqpc0000001713439805334', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 64, 'name': 'srno=b_1_28', 'dir': 'c8', 'linked': 2, 'url': 'https://www.flipkart.com/bolas-seedless-tunisian-dates/p/itm9a4a99b4acfdc?pid=NDFGXVVBQRGYT4TC&lid=LSTNDFGXVVBQRGYT4TCLHURLP&marketplace=FLIPKART&store=eat/ltb&srno=b_1_28&otracker=browse&fm=organic&iid=en_id1m4MMKmeogfDFhupCa1sVpEhOai6z-vIj6BI5vYggPr0IGA6voo_XR1kyY7tzRLHBhCyBwOQMdU_NMdCmiZEKsf8s6I2Oz2HOgbXTo_9U%3D&ppt=None&ppn=None&ssid=usqtd7yqpc0000001713439805334', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 64, 'name': 'ssid=usqtd7yqpc0000001713439805334', 'dir': 'c9', 'linked': 2, 'url': 'https://www.flipkart.com/bolas-seedless-tunisian-dates/p/itm9a4a99b4acfdc?pid=NDFGXVVBQRGYT4TC&lid=LSTNDFGXVVBQRGYT4TCLHURLP&marketplace=FLIPKART&store=eat/ltb&srno=b_1_28&otracker=browse&fm=organic&iid=en_id1m4MMKmeogfDFhupCa1sVpEhOai6z-vIj6BI5vYggPr0IGA6voo_XR1kyY7tzRLHBhCyBwOQMdU_NMdCmiZEKsf8s6I2Oz2HOgbXTo_9U%3D&ppt=None&ppn=None&ssid=usqtd7yqpc0000001713439805334', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 64, 'name': 'store=eat/ltb', 'dir': 'c10', 'linked': 2, 'url': 'https://www.flipkart.com/bolas-seedless-tunisian-dates/p/itm9a4a99b4acfdc?pid=NDFGXVVBQRGYT4TC&lid=LSTNDFGXVVBQRGYT4TCLHURLP&marketplace=FLIPKART&store=eat/ltb&srno=b_1_28&otracker=browse&fm=organic&iid=en_id1m4MMKmeogfDFhupCa1sVpEhOai6z-vIj6BI5vYggPr0IGA6voo_XR1kyY7tzRLHBhCyBwOQMdU_NMdCmiZEKsf8s6I2Oz2HOgbXTo_9U%3D&ppt=None&ppn=None&ssid=usqtd7yqpc0000001713439805334', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 }
];
