var child = [
  { 'dupe': false, 'type': 8, 'name': 'ewaste-compliance-tnc', 'dir': 'c0', 'linked': 2, 'url': 'https://www.flipkart.com/pages/ewaste-compliance-tnc', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 8, 'name': 'grievance-redressal-mechanism', 'dir': 'c1', 'linked': 2, 'url': 'https://www.flipkart.com/pages/grievance-redressal-mechanism', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 8, 'name': 'paymentsecurity', 'dir': 'c2', 'linked': 2, 'url': 'https://www.flipkart.com/pages/paymentsecurity', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 8, 'name': 'privacypolicy', 'dir': 'c3', 'linked': 2, 'url': 'https://www.flipkart.com/pages/privacypolicy', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 8, 'name': 'returnpolicy', 'dir': 'c4', 'linked': 2, 'url': 'https://www.flipkart.com/pages/returnpolicy', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 8, 'name': 'terms', 'dir': 'c5', 'linked': 2, 'url': 'https://www.flipkart.com/pages/terms', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'cancellation-tnc', 'dir': 'c6', 'linked': 2, 'url': 'https://www.flipkart.com/pages/cancellation-tnc', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'no-return-products', 'dir': 'c7', 'linked': 2, 'url': 'https://www.flipkart.com/pages/no-return-products', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'no_returns', 'dir': 'c8', 'linked': 1, 'url': 'https://www.flipkart.com/pages/no_returns', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'payments', 'dir': 'c9', 'linked': 2, 'url': 'https://www.flipkart.com/pages/payments', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'reseller-return-policy-may21', 'dir': 'c10', 'linked': 2, 'url': 'https://www.flipkart.com/pages/reseller-return-policy-may21', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'shipping', 'dir': 'c11', 'linked': 2, 'url': 'https://www.flipkart.com/pages/shipping', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 }
];
